### ISSUE TITLE
Can't access bitbucket.org/Odysseus/arachnefront.git/

### ISSUE THREAD

**Issue by god830novo** [OHDSI/ArachneUI#547]
The following instruction doesn't work
After initiating project copy community code into community-src folder:
git clone https://bitbucket.org/Odysseus/arachnefront.git community-src

Cloning into 'community-src'...
remote: Forbidden
fatal: unable to access 'https://bitbucket.org/Odysseus/arachnefront.git/': The requested URL returned error: 403

**Comment by acumarav** [comment]
Hello @god830novo, 
I am not sure why do you refer to the bitbucket but the actual Arachne frontend application is on the github.
You might clone it from the github repo:  https://github.com/OHDSI/ArachneUI
