### ISSUE TITLE
Chart wrong display in Dashboard reports

### ISSUE THREAD

**Issue by spbima** [OHDSI/ArachneUI#621]
Chart wrong display in Dashboard reports

https://www.arachnenetwork.com/data-catalog/data-sources/36/profile

AGE AT FIRST OBSERVATION

![arachne-ds-dashboard-1](https://user-images.githubusercontent.com/804934/55892135-6b159080-5bbe-11e9-9d31-1e585c5d3959.jpg)

PERSONS WITH CONTINUOUS OBSERVATION BY MONTH

![arachne-ds-dashboard-2](https://user-images.githubusercontent.com/804934/55891972-2ab61280-5bbe-11e9-927d-4560bd17ffa4.jpg)

**Comment by pavgra** [comment]
Fixed for "Import" by https://github.com/OHDSI/ArachneNodeAPI/pull/305
