### ISSUE TITLE
Analysis reordering fails

### ISSUE THREAD

**Issue by pavgra** [OHDSI/ArachneUI#632]
![arachne-analysis-reorder](https://user-images.githubusercontent.com/10010071/57180772-21853200-6e5a-11e9-91c2-3534cf052ddd.gif)

**Comment by acumarav** [comment]
Problem occur during conversion between Study - StudyDTO, PR has been submitted:
https://github.com/OHDSI/ArachneCentralAPI/pull/597

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/ArachneCentralAPI/pull/597
