### ISSUE TITLE
Run the UI as a static site

### ISSUE THREAD

**Issue by blootsvoets** [OHDSI/ArachneUI#791]
In many deployments of frontends I tend to serve the UI as a static site. That way the server implementation is mostly independent from the code base: node can be used but also Nginx, Apache2 or tomcat.

Is serving ArachneUI as an independent server mode possible/supported?

**Comment by wivern** [comment]
@blootsvoets Technically I don't see any reasons that might prevent to build and deploy ArachneUI as a static content to any suitable http server. But currently independent server mode isn't officially supported and was never tested.

**Comment by blootsvoets** [comment]
Thanks for your answer. I'll try the node server then. #790 is blocking me on that though.
